### ISSUE TITLE
Module not found: Error: Can't resolve 'vue-chartjs'

### ISSUE THREAD

**Issue by Pixelsplasher** [pcegnar/admin#12]
Vue-ChartJS is a dependency for
\resources\js\components\common\BarChart.vue
  2,38: import { Line, HorizontalBar } from 'vue-chartjs'
\resources\js\components\common\Chart.vue
  2,38: import { Line, HorizontalBar } from 'vue-chartjs'

Try
npm install vue-chartjs chart.js --save

**Comment by pcegnar** [comment]
this issue has been fixed  as of sprint 4 test cycle; module had been added to latest package. thanks @Pixelsplasher
